manifest:
  remotes:
    - name: customboard
      url-base: https://github.com/hjw1112/customboard-zmk-config
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: customboard-zmk-config
      remote: custom
      revision: main
  self:
    path: config
